version: '3.7'

services:
  worker:
    build: .
    image: mxmp/swtoolz-core
    command: [python, swtoolz-core.py, nodaemon]
    ports:
      - "7377:7377"
    volumes:
      - ~/swconfig.py:/app/swconfig.py
      - ~/swtoolz-core.log:/var/log/swtoolz-core.log