version: '3.7'

services:
  worker:
    build: .
    image: mxmp/swtoolz-core
    restart: always
    ports:
      - "7377:7377"
    volumes:
      - ~/swconfig.py:/app/swconfig.py
      - ~/swtoolz-core.log:/var/log/swtoolz-core.log
      - ./:/app

networks:
  default:
    ipam:
      config:
      - subnet: 172.28.0.0/16